CREATE TABLE IF NOT EXISTS bots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  coins JSONB NOT NULL,
  allocations JSONB NOT NULL,
  trigger_type TEXT NOT NULL,
  threshold_value REAL,
  time_interval BIGINT,
  initial_investment REAL NOT NULL,
  current_value REAL NOT NULL,
  created_at BIGINT NOT NULL,
  last_rebalance_at BIGINT NOT NULL,
  trigger_prices JSONB,
  take_profit REAL,
  stop_loss REAL
);

CREATE TABLE IF NOT EXISTS holdings (
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  coin TEXT NOT NULL,
  amount REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS simulated_trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  coin TEXT NOT NULL,
  side TEXT NOT NULL,
  amount REAL NOT NULL,
  price REAL NOT NULL,
  fee REAL NOT NULL,
  reason TEXT NOT NULL DEFAULT 'initial',
  timestamp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS portfolio_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  total_value_usd REAL NOT NULL,
  timestamp BIGINT NOT NULL
);
